name: JuliaFormatter

on:
  push:
    branches:
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check if git repo
      run: |
        git status
        ls -a
    - uses: julia-actions/julia-format@master
      with:
        args: -v .
